[package]
name = "rust-ieee802154-gen"
version = "0.1.0"
edition = "2018"

[dependencies]
prot2rust = { git = "https://github.com/rudihorn/prot2rust" }
log = { version = "~0.4", features = ["std"] }
proc-macro2 = "1.0"
anyhow = "1.0"
